### ISSUE TITLE
Builds fail with PIO_ENABLE_TIMING turned OFF

### ISSUE THREAD

**Issue by jayeshkrishna** [E3SM-Project/scorpio#476]
@xylar noticed that SCORPIO builds fail with PIO_ENABLE_TIMING turned off (GPTL lib is not available on these builds) when building MPAS.

The tests, tools builds fail with error messages related to missing gptl.h and the gptl library,
```
...
[ 18%] Building C object tests/cunit/CMakeFiles/test_req_block_wait.dir/test_common.c.o
cd /home/jayesh/scorpio_build/tests/cunit && /nfs/gce/projects/climate/software/mpich/3.4.2/gcc-11.1.0/bin/mpicc -DCPRGNU -DLOGGING -DMPICH_SKIP_MPICXX -DNETCDF_C_LOGGING_ENABLED -DNETCDF_C_NC__ENDDEF_EXISTS -DOMPI_SKIP_MPICXX -DTIMING -DUSE_PNETCDF_VARN -DUSE_PNETCDF_VARN_ON_READ -I/home/jayesh/scorpio3/tests/cunit -I/home/jayesh/scorpio_build/src/clib -I/nfs/gce/projects/climate/software/netcdf/4.8.1c-4.3.1cxx-4.5.3f-parallel/mpich-3.4.2/gcc-11.1.0/include -I/nfs/gce/projects/climate/software/hdf5/1.12.1/mpich-3.4.2/gcc-11.1.0/include -I/nfs/gce/projects/climate/software/pnetcdf/1.12.2/mpich-3.4.2/gcc-11.1.0/include -I/home/jayesh/scorpio3/src/clib -g -O0 -Wall -std=c99 -fsanitize=address -fno-omit-frame-pointer -std=c99 -g -O0 -g -MD -MT tests/cunit/CMakeFiles/test_req_block_wait.dir/test_common.c.o -MF CMakeFiles/test_req_block_wait.dir/test_common.c.o.d -o CMakeFiles/test_req_block_wait.dir/test_common.c.o -c /home/jayesh/scorpio3/tests/cunit/test_common.c
In file included from /home/jayesh/scorpio3/tests/cunit/test_req_block_wait.c:3:
/home/jayesh/scorpio3/src/clib/pio_internal.h:28:10: fatal error: gptl.h: No such file or directory
   28 | #include <gptl.h>
      |          ^~~~~~~~
compilation terminated.
...
```
To reproduce build SCORPIO with
```
cmake \
-DPIO_ENABLE_TOOLS:BOOL=ON \
-DPIO_ENABLE_EXAMPLES:BOOL=ON \
-DPIO_ENABLE_TESTS:BOOL=ON \
-DPIO_ENABLE_TIMING:BOOL=OFF \
...
```
SCORPIO 1.3.2 has the above issue. The above build works fine with SCORPIO 1.2.2

**Comment by xylar** [comment]
Much appreciated!
